const sessionsHistory = [
  {
    id: 1,
    currentCondition: {
      mainComplaint: "knee pain",
      painCharacteristics: {
        onset: "suden",
        duration: "2 weeks",
        type: "burning",
        intensity: 0,
        location: "left knee",
        aggravatingFactors: ["Running", "Stairs"],
        relievingFactors: ["rest"],
      },
      associatedSymptoms: ["Swelling", "Bruising"],
      functionalLimitations: ["Difficulty walking", "Limited range of motion"],
    },
    lifestyle: {
      physicalActivity: {
        type: "Running",
        frequency: "3 times a week",
        intensity: "Moderate",
      },
      smoking: {
        status: false,
        frequency: "10 cigarettes per day",
      },
      alcoholConsumption: {
        status: false,
        frequency: "",
      },
      diet: "Balanced",
      sleep: {
        hoursPerNight: 0,
        quality: "Interrupted",
      },
    },
    diagnostic: "tendinitis rotuliana",
    sessionsDates: {
      session: 1,
      date: "",
      hour: "",
      session: 2,
      date: "",
      hour: "",
      session: 3,
      date: "",
      hour: "",
      session: 4,
      date: "",
      hour: "",
      session: 5,
      date: "",
      hour: "",
      session: 5,
      date: "",
      hour: "",
      session: 7,
      date: "",
      hour: "",
      session: 8,
      date: "",
      hour: "",
      session: 9,
      date: "",
      hour: "",
      session: 10,
      date: "",
      hour: "",
    },
    start: "10/01/2024",
    end: "10/01/2024",
    active: true,
    sessions: [
      {
        number: 1,
        date: "10/01/2024",
        hour: "15:50",
        dailyReview: [
          {
            BloodPressure: "",
            saturation: 0,
            heartRate: 0,
            bodyWeight: 0,
            additionalInformation: "",
          },
        ],
        warmUp: [
          {
            name: "trote",
            rounds: 1,
            sets: 0,
            reps: 0,
            break: 1,
            duration: 10,
            weight: 0,
            images: [
              "https://i0.wp.com/quiurevista.com/wp-content/uploads/2023/06/man-and-woman-running-jogging.jpg?resize=598%2C490&ssl=1",
            ],
            videos: ["https://www.youtube.com/shorts/fifXz14a5Ko"],
          },
        ],
        workOut: [
          {
            name: "sentadillas",
            rounds: 1,
            sets: 3,
            reps: 10,
            break: 1,
            duration: 0,
            weight: 80,
            images: ["https://i.blogs.es/93405c/sentadilla/1366_2000.webp"],
            videos: ["https://www.youtube.com/watch?v=VRKdOsad3HQ"],
          },
        ],
        coolDown: [
          {
            name: "respiraciones",
            rounds: 0,
            sets: 0,
            reps: 0,
            break: 0,
            duration: 5,
            weight: 0,
            images: ["https://i.blogs.es/93405c/sentadilla/1366_2000.webp"],
            videos: [
              "https://www.fem.es/wp-content/webp-express/webp-images/uploads/2019/01/1_ejercicios_respiratorios.png.webp",
            ],
          },
        ],
      },
      {
        number: 2,
        date: "10/01/2024",
        hour: "15:50",
        warmUp: [
          {
            name: "trote",
            rounds: 1,
            sets: 0,
            reps: 0,
            break: 1,
            duration: 10,
            weight: 0,
            images: [
              "https://i0.wp.com/quiurevista.com/wp-content/uploads/2023/06/man-and-woman-running-jogging.jpg?resize=598%2C490&ssl=1",
            ],
            videos: ["https://www.youtube.com/shorts/fifXz14a5Ko"],
          },
        ],
        workOut: [
          {
            name: "sentadillas",
            rounds: 1,
            sets: 3,
            reps: 10,
            break: 1,
            duration: 0,
            weight: 80,
            images: ["https://i.blogs.es/93405c/sentadilla/1366_2000.webp"],
            videos: ["https://www.youtube.com/watch?v=VRKdOsad3HQ"],
          },
        ],
        coolDown: [
          {
            name: "respiraciones",
            rounds: 0,
            sets: 0,
            reps: 0,
            break: 0,
            duration: 5,
            weight: 0,
            images: ["https://i.blogs.es/93405c/sentadilla/1366_2000.webp"],
            videos: [
              "https://www.fem.es/wp-content/webp-express/webp-images/uploads/2019/01/1_ejercicios_respiratorios.png.webp",
            ],
          },
        ],
      },
    ],
  },
  {
    id: 2,
    start: "10/01/2024",
    end: "10/01/2024",
    active: true,
    sessions: [
      {
        number: 1,
        date: "10/01/2024",
        hour: "15:50",
        warmUp: [
          {
            name: "trote",
            rounds: 1,
            sets: 0,
            reps: 0,
            break: 1,
            duration: 10,
            weight: 0,
            images: [
              "https://i0.wp.com/quiurevista.com/wp-content/uploads/2023/06/man-and-woman-running-jogging.jpg?resize=598%2C490&ssl=1",
            ],
            videos: ["https://www.youtube.com/shorts/fifXz14a5Ko"],
          },
        ],
        workOut: [
          {
            name: "sentadillas",
            rounds: 1,
            sets: 3,
            reps: 10,
            break: 1,
            duration: 0,
            weight: 80,
            images: ["https://i.blogs.es/93405c/sentadilla/1366_2000.webp"],
            videos: ["https://www.youtube.com/watch?v=VRKdOsad3HQ"],
          },
        ],
        coolDown: [
          {
            name: "respiraciones",
            rounds: 0,
            sets: 0,
            reps: 0,
            break: 0,
            duration: 5,
            weight: 0,
            images: ["https://i.blogs.es/93405c/sentadilla/1366_2000.webp"],
            videos: [
              "https://www.fem.es/wp-content/webp-express/webp-images/uploads/2019/01/1_ejercicios_respiratorios.png.webp",
            ],
          },
        ],
      },
    ],
  },
];

const personalData = {
  surname: "Perez",
  name: "Juan",
  oS: "OSMECON",
  nOS: "4092790578",
  address: "El payador",
  addressNumber: "1234",
  dToPiso: "2",
  dto: "a",
  localidad: "villa bosch",
  provincia: "Buenos Aires",
  pais: "arentina",
  cP: "1682",
  telPart: "45678902",
  telCel: "1156783456",
  fechaNacimiento: "23-4-56",
  edad: "68",
  dni: "34564456",
  profesion: "striper",
  profDerivante: "doctor petroca",
  matPrfDeriv: "mn34567",
  peso: "90",
  talla: "170",
};
const personalHistory = {
  medicalConditions: [
    { name: "diabetes", observations: "", date: "" },
    { name: "diabetes", observations: "", date: "" },
  ],
  medications: [
    { name: "diabetes", observations: "", date: "" },
    { name: "diabetes", observations: "", date: "" },
  ],
  allergies: [{ name: "diabetes", observations: "", date: "" }],
  previousInjuries: [{ name: "diabetes", observations: "", date: "" }],
  surgeries: [
    { id: 1, name: "tendinitis rotuliana", date: "", observations: "" },
  ],
};

const familyHistory = [
  {
    relationship: "father",
    disease: ["patologia 1", "patologia 2"],
  },
  {
    relationship: "mather",
    disease: ["patologia 1", "patologia 2"],
  },
];
