POST https://kinapp-api.vercel.app/api/create-admin
Content-Type: application/json

{
  "userName": "admin",
  "email": "orkinoa@gmail.com",
  "cellPhone":"1158060332",
  "password": "securePassword123",
  "confirmPassword": "securePassword123",
  "roles": "admin",
  "permissions": {
    "manageUsers": true,
    "manageClients": true,
    "manageCourses": true,
    "manageAppointments": true
  },
  "isSuperAdmin": false
}
###
POST https://kinapp-api.vercel.app/api/admins/verify-email
Content-Type: application/json

{
    "otp":"6552",
    "adminId":"67d1e6b6fd7042effdc19cd4"
}
###
POST https://kinapp-api.vercel.app/api/admins/forgot-password
Content-Type: application/json

{
    "email":"orkinoa@gmail.com"
}
###
POST https://kinapp-api.vercel.app/reset-password?token=b8d71c6d1590804f30eba09e92c147853cf9800e0c2bdc0acb8805b78931&id=64a57e078ce2031475ae56aa
Content-Type: application/json

{
    "password": "87654321"
}