POST http://localhost:3001/sign-in
Content-Type: application/json

{
    "email": "ferbassino@gmail.com",
    "password": "12345678"
}
###
POST https://kinapp-api.vercel.app/sign-in
Content-Type: application/json

{
    "email": "ferbassino@gmail.com",
    "password": "12345678"
}