POST http://localhost:3001/api/client/create
Content-Type: application/json

{
    "email":"mengano@gmail.com",
    "password":"0OwViH47",
    "sessionsHistory": [
    {
      "id": 1,
      "currentCondition": {
        "mainComplaint": "shoulder pain",
        "painCharacteristics": {
          "onset": "suden",
          "duration": "2 weeks",
          "type": "burning",
          "intensity": 0,
          "location": "left knee",
          "aggravatingFactors": ["Running", "Stairs"],
          "relievingFactors": ["rest"]
        },
        "associatedSymptoms": ["Swelling", "Bruising"],
        "functionalLimitations": ["Difficulty walking", "Limited range of motion"]
      },
      "lifestyle": {
        "physicalActivity": {
          "type": "Running",
          "frequency": "3 times a week",
          "intensity": "Moderate"
        },
        "smoking": {
          "status": false,
          "frequency": "10 cigarettes per day"
        },
        "alcoholConsumption": {
          "status": false,
          "frequency": ""
        },
        "diet": "Balanced",
        "sleep": {
          "hoursPerNight": 0,
          "quality": "Interrupted"
        }
      },
      "diagnostic": "tendinitis rotuliana",
      "start": "10/01/2024",
      "end": "10/01/2024",
      "active": true,
      "dailyReview":[],
      "sessions": [
        
      ]
    }
  ],
  "personalData": {
    
  },
  "personalHistory": {
    
  },
  "familyHistory": [
    
  ],
    "birthDate":50,
    "weight":80,
    "size":170,
    "gender":"female",
    "pALevel":"low",
    "userId":"65fdd605d47aad0cb6c15314",
    "roles":"bronze",
    "data":{
        "name":"fernado",
        "surname":"bassino"
    }
}